config/routes.rb
Rails.application.routes.draw do

  root :to => 'skills#index'

   resources :skills do
     resources :projects, only: [:new, :create]
end
   resources :projects, only: [:index, :show, :edit, :update, :destroy]

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/deutsch'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :link, presence: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def deutsch
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new
  end

  def create
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully added!"
      redirect_to skill_path(@project.skill)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project successfully updated."
      redirect_to project_path
    else
      render :edit
    end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    flash[:notice] = "Project successfully deleted."
    redirect_to projects_path
  end

private
  def project_params
    params.require(:project).permit(:name, :description, :link)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      flash[:notice] = "Skill successfully added!"
      redirect_to skill_path(@skill)
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      flash[:notice] = "Skill successfully updated."
      redirect_to skills_path
    else
      render :edit
    end
  end

  def destroy
    skill = Skill.find(params[:id])
    skill.destroy
    flash[:notice] = "Skill successfully deleted."
    redirect_to skills_path
  end

private

  def skill_params
    params.require(:skill).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>All forms must be filled:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismisable text-center alert-custom" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismisable text-center alert-custom" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- <div class="ember-body"> -->
  <div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/pages/deutsch">Deutsch?</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", pages_home_path %></li>
        <li class="active"><%= link_to "Skills", skills_path %></li>
        <li class="active"><a href="/projects">Projects</a></li>
        <li class="active"><%= link_to "About", pages_about_path %></li>
        <li class="active"><%= link_to "Contact", pages_contact_path %></li>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="navbar">
    <%= render 'layouts/navbar' %>
  </div>   

  <div class="container">
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>What is this?</h1>
<p>This is a Ruby on Rails app that is a work in progress as coursework for my Epicodus class. I'm enjoying the journey as I learn RoR while building this app. It's fun, and at times torturous. Right now I'm feeling the fun a bit more than the torture, but ask me again tomorrow and I may have a different answer!</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<h3>I'll update this super boring "contact" page soon, I promise!</h3>

<p>In the meantime, here you go:</p>
<p>Jessi Iler</p>
<p>Vancouver, WA</p>
<p>Email: inertial.observer@gmail.com</p>
<p>Github: https://github.com/InertialObserver</p>

<h4>Just for fun:</h4>

<a href="#" onclick="this.style.backgroundColor='#990000'">Paint it red</a>

app/views/pages/deutsch.html.erb
<h1>Sprechen Sie Deutsch?</h1>
<p>Ja?</p>
<p>Ich auch!</p>
<p>Okay, vielleicht spreche ich nur ein bisschen Deutsch aber das wichtigste aller Dinge kommunizieren ist.</p> 

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>This will be the app's home page. For now, it's just sitting here holding down the fort until I'm ready to fix the routes.</p>

app/views/projects/_form.html.erb
<%= form_for [@skill, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<p><%= link_to "Home", skills_path %></p>
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= content_for(:title, "Projects") %>
<p><%= link_to "Home", skills_path %></p>

<div class="container">
  <h1>Projects</h1>

<ul>
  <% if @projects.any? %>

  <% @projects.each do |project| %>

  <li><%= link_to project.name, project_path(project) %></li>
  <% end %>
</ul>

  <% else %>
    <p>There are no projects yet.</p>
  <% end %>
</div>

app/views/projects/new.html.erb
<p><%= link_to "Home", skills_path %></p>
<%= render 'layouts/errors', object: @project %>
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= content_for(:title, @project.name) %>

<p><%= link_to "Home", skills_path %></p>

<h3>
  <%= link_to @project.name, edit_project_path(@project) %>
  <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, project_path(@project), data: {confirm: "Are you sure?", method: "delete"} %>
  <h4><%= @project.description %></h4>
  <a href><%= @project.link %></a>
</h3>

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render 'form' %>

app/views/skills/index.html.erb
<%= content_for(:title, "Skills") %>
<div class="container">
<h1>Skills</h1>
<ul>
  <% @skills.each do |skill| %>
    <li><%= link_to skill.name, skill_path(skill) %></li>
  <% end %>
</ul>
</div>

<p><%= link_to "Create a new skill", new_skill_path %></p>

app/views/skills/new.html.erb
<%= render 'layouts/errors', object: @skill %>
<h1>New Skill</h1>


<%= render 'form' %>

app/views/skills/show.html.erb
<%= content_for(:title, @skill.name) %>

<p><%= link_to "Home", skills_path %></p>

<h1>
  <%= link_to @skill.name, edit_skill_path(@skill) %>
  <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, skill_path(@skill), data: {confirm: "Are you sure?", method: "delete"} %>
</h1>
  <ul>
  <li><%= @skill.description %></li>
</ul>

<p><%= link_to "Add a project", new_skill_project_path(@skill) %> </p>

<ul>
  <% if @skill.projects.any? %>

  <% @skill.projects.each do |project| %>

  <li><%= link_to project.name, project_path(project) %></li>
<% end %>

<% else %>
  <p>There are no projects yet.</p>
<% end %>